### ISSUE TITLE
Changement nom métabolite - QC

### ISSUE THREAD

**Issue by amrocher** [llegregam/MSReader#10]
Hello, depuis le changement de noms de métabolites l'Orotate n'apparait plus dans les métabolites QC des métabolites centraux. Il faudrait changer la recherche du métabolite initialement appelé "Oro" en "Orotate".
Merci beaucoup !

**Comment by llegregam** [comment]
Le changement de nom de l'Orotate à été pris en compte dans la dernière mise à jour 1.1.2.
Cloture de l'issue.
