### ISSUE TITLE
Noms colonnes pour coller à GraphStatsR

### ISSUE THREAD

**Issue by amrocher** [llegregam/MSReader#28]
Hello,
Depuis la mise à jour de GraphStatsR, on a besoin que le nom des colonnes soient strictement ceux-ci : features, type, unit (actuellement : Features, type, Unit). Est-ce que tu peux les modifier dans la sortie "output_for_graphstat.tsv" s'il te plait ?
Merci
Amandine

**Comment by llegregam** [comment]
Une nouvelle version est en ligne qui devrait apporter les changements souhaités. N'hésite pas à me dire si jamais tu vois un beug :)

**Comment by amrocher** [comment]
au top merci je te dirais :)
