### ISSUE TITLE
Nouveau fichier sortie

### ISSUE THREAD

**Issue by amrocher** [llegregam/MSReader#34]
Comme discuté ensemble au téléphone et après avoir rebouclé avec Floriant : il faudrait créer un nouveau fichier de sortie exclusivement pour les ACP, qui ne serait pas diffusé aux demandeurs. Il s'appellera "output_for_graphstats_ACP", il contiendra uniquement les aires C12, aires C13 et ratios C12/C13 des métabolites et remplacera tous les NA par 0.

Merci :)

**Comment by llegregam** [comment]
C'est bon la mise à jour a été faite :)
