### ISSUE TITLE
Export output_for_graphstat pour les ACP

### ISSUE THREAD

**Issue by amrocher** [llegregam/MSReader#38]
Salut Loïc,

Est-ce qu'il serait possible d'exporter le fichier output_for_graphstat pour les ACP sous un autre nom que le output_for_graphstat originel ? Car si on exporte les deux, ils portent le même nom donc ils s'écrasent. Tu peux l'exporter sous le nom output_for_graphstat_ACP par exemple :)

Merci
Amandine

**Comment by llegregam** [comment]
Normalement c'est bon, tu peux tester et me faire un retour? :)

**Comment by amrocher** [comment]
Hello, il génère bien deux fichiers distincts merci. Je verrai à l'usage si tout est ok, j'ai juste fait un test d'export de fichiers. Ticket clos :)

**Comment by llegregam** [comment]
Au top!!
