### ISSUE TITLE
Metabolites remover

### ISSUE THREAD

**Issue by amrocher** [llegregam/MSReader#5]
Salut Loïc, quand j'enlève des métabolites de mes data grâce au "metabolites remover", ils n'apparaissent pas dans la table finale sauf dans l'onglet "Report" où ils y sont toujours. Ce serait possible de les enlever de cet onglet également s'il te plait ? Merci :)

**Comment by llegregam** [comment]
Salut Amandine, le beug a été réparé et l'outil va être mis à jour (v1.1.1) avec le bugfix.
