### ISSUE TITLE
Utilisation de la colonne "Normalized Area" pour les ratios C12/C13 (Skyline)

### ISSUE THREAD

**Issue by amrocher** [llegregam/MSReader#56]
Pour extraire les ratios C12/C13 il faudrait que MSReader utilise la colonne "Normalized Area" de la sortie Skyline car la colonne "Ratio Ligh to Heavy" ne prend pas en compte la subrogation d'un signal C13, et recalculer le ratio a posteriori avec les aires C12 et les aires C13 (heavy) associées ne prend pas en compte la subrogation du signal C13 non plus.

Merci :)

**Comment by amrocher** [comment]
On en est où sur cette issue la team MSReader ? :)

**Comment by llegregam** [comment]
Pour l'instant les priorités sont sur le rapport et la soutenance de RKO, mais tqt nous n'avons pas oublié ;)
